const assert = require('assert');
const S = require('../assets/js/seido-date.js');
function calc(input){return S.calculatePrimaryDate({season_year:2026,theme:'love_contact',client_words:'',client_desired_date:'',additional_cards:'',...input}).internal;}
let r=calc({decan_card:'The Emperor',day_key_card_type:'numbered',day_key_card_suit:'Wands',day_key_card_rank:'3'});
assert.strictEqual(r.primary_window_start,'2026-03-30'); assert.strictEqual(r.primary_window_end,'2026-04-08'); assert.strictEqual(r.primary_date,'2026-04-03'); assert.strictEqual(r.confidence_level,'high');
r=calc({decan_card:'Wands 3',day_key_card_type:'major',day_key_card_suit:'Major',day_key_card_rank:'Major',day_key_card_number:'4'});
assert.strictEqual(r.primary_window_start,'2026-03-30'); assert.strictEqual(r.primary_window_end,'2026-04-08'); assert.strictEqual(r.primary_date,'2026-04-03'); assert.strictEqual(r.confidence_level,'high');
r=calc({decan_card:'Wands 3',day_key_card_type:'numbered',day_key_card_suit:'Wands',day_key_card_rank:'3'});
assert.strictEqual(r.primary_window_start,'2026-03-30'); assert.strictEqual(r.primary_window_end,'2026-04-08'); assert.strictEqual(r.confidence_level,'high');
r=calc({decan_card:'The Emperor',day_key_card_type:'major',day_key_card_suit:'Major',day_key_card_rank:'Major',day_key_card_number:'6'});
assert.strictEqual(r.primary_window_start,'2026-03-20'); assert.strictEqual(r.secondary_windows[0].start,'2026-05-21'); assert.strictEqual(r.calculation_mode,'separated_windows'); assert.strictEqual(r.confidence_level,'caution');
r=calc({decan_card:'Wands 3',day_key_card_type:'numbered',day_key_card_suit:'Cups',day_key_card_rank:'5'});
assert.strictEqual(r.primary_window_start,'2026-03-30'); assert.strictEqual(r.secondary_windows[0].start,'2026-10-23'); assert.strictEqual(r.calculation_mode,'separated_windows');
r=calc({decan_card:'The Emperor',day_key_card_type:'major',day_key_card_suit:'Major',day_key_card_rank:'Major',day_key_card_number:'16'});
assert.strictEqual(r.primary_window_start,'2026-03-20'); assert.ok(r.calculation_note.includes('直接の日付対応を持たない'));
r=calc({decan_card:'The Emperor',day_key_card_type:'numbered',day_key_card_suit:'Wands',day_key_card_rank:'3',client_desired_date:'2026-04-05'});
assert.strictEqual(r.primary_window_start,'2026-03-30'); assert.strictEqual(r.primary_date,'2026-04-05'); assert.strictEqual(r.desired_date_status,'inside_primary');
r=calc({decan_card:'The Emperor',day_key_card_type:'numbered',day_key_card_suit:'Wands',day_key_card_rank:'3',client_desired_date:'2026-10-18'});
assert.strictEqual(r.primary_date,'2026-04-03'); assert.strictEqual(r.desired_date_status,'outside_all');
r=calc({decan_card:'The Devil',day_key_card_type:'numbered',day_key_card_suit:'Pentacles',day_key_card_rank:'3',client_desired_date:'2026-01-05'});
assert.strictEqual(r.period_card.start,'2025-12-21'); assert.strictEqual(r.day_key_card.start,'2025-12-31'); assert.strictEqual(r.primary_window_start,'2025-12-31'); assert.strictEqual(r.primary_window_end,'2026-01-09'); assert.strictEqual(r.primary_date,'2026-01-05');
r=calc({season_year:2026,decan_card:'The Star',day_key_card_type:'numbered',day_key_card_suit:'Swords',day_key_card_rank:'6'});
assert.strictEqual(r.period_card.start,'2027-01-20'); assert.strictEqual(r.day_key_card.start,'2027-01-30'); assert.strictEqual(r.primary_window_start,'2027-01-30'); assert.strictEqual(r.primary_window_end,'2027-02-08');
console.log('seido-date tests passed');
